language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: QYrBgo4vbYu3cpNfJd2jGJHLLFID3bG1fJFmRl3NzwRwGf05GkNWwNa8XZIMdmioCnd6RC6x2GYqolnIDYmJPS2P/oCwFLp6oMyFUwNY4njCm4RtirxnKFkaEwEwvNHq4bO0acDtmQ/bPljUXjxsul5TGgBYASSQUfAv5n62mlPkFnu+LT55DnO5wJh6HMSQCPGty7diz4CGx/hsQnnKmmL3nqTz90cUpXVHfkaxPH4MS1vED9IWC0fiMXobqv3oQchukowTiMvae5iTGN7iVtWJAFDEziKr6FBmAUW9QUsps3RRBwPn1T9mWlYng1oIhLryu0jvAvrjP/YvhjxYV+dmaBkNBvhWoLvt3C46YjFb0xoF7aQBhxoZIVR8ng3G+zl7b0RSIxq2axnBtbSRtZ/q2Hr0I+eT5+jn7LYTnDNxucouV3hpoI6ZC5tssWwgcZUQO6t0kSME0qf3EXkeHMqM3KwQgw2jn4ADsiradNKeexWnBfh/vwh6UJ0WKBNzUIB1v4vcLYs5XwlZzmj/twzZkn1wAZwmImrtjHf12waApDvNkLx6U4e/l7RMXWEDVEUV+mKKI9I6RMLuavjYZMaKfJOb3PbT/tdbLH4Lb7EJ2kGkvmFuiATnNwzUB3Ev6uY9VFJv0zD4jLCXFbQQQ0MEI1DUmRToVGfQ/n3G0V8=
  app: fast-peak-68791
  on:
    repo: lightsage88/gdc2api
