language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: PKWi5LzyJGzACK0IFN2Ar6IiQAQ6WjPwXaTGyjMuG8m691Aac2RXBXHVqKNGZSFcy72e9tuksofxfaF9D4TYd6XGSRqJZiiehU3sT5P3L+1e3I+aXtiTVkqy6e1qyrY3caBvIFHiZ2cchYLs0UXGtKJTOnRMYkbXxrtLSpdx0d5xhs3JiBjziKtCN8djW9E3Zc9WDjT/O1s3ykq+/hNDGfQNNHDIik9G+ij+lRUcPZHVOHlL6t0+1/Vyib4jEP2AJY5pTwfqFxZgmiDctwsnFgqCBKEXX1R3dz33EicOCY/LwL72KbdQe0XjRQUiVPyst/4CjMhw5USUIp2HUk9SUJ6voGQ6z/flBK3hUckRMZrDTm1OznpDyrp9LDSCE2GOY7t+IcMu2hFzE7eWoLL2k573Q/xfH7yyHGwm2s4JAyuoqyoAo8UFyzmqvKQCpYeqTBqQSIM4mYV3H5oVklXJLleb7ia9mkdLs46tCv4LMvYfUuk71PdJiMrMhYktdcmfazQz2S57DTOwaxOV3NXf4BrauIwCI3tX0lJzfKRCQnq8unKjAT5iVgNzN19x00d12cB4S71+zfy6EbeQHIZD9+gXC38ygGZyakrrvhOikqsbNE0t5H35dR62J2mIS3SsaJXol334CyaMDflATmocoKQI+Ynt3qhYiDin/2jsvCU=
  app: fast-peak-68791
  on:
    repo: lightsage88/gdc2api
